// <auto-generated />
namespace The2r.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NullableActivityAttendance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullableActivityAttendance));
        
        string IMigrationMetadata.Id
        {
            get { return "201701250503218_NullableActivityAttendance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
